version: "3.8"

services:
  scum:
    build: .
    container_name: SCUM-SV1
    network_mode: host
    volumes:
      - /mnt/user/appdata/SCUM-SV1:/home/scum/SCUM
    environment:
      TZ: Asia/Bangkok
      STEAM_USER: your_steam_user
      STEAM_PASS: your_steam_password
      SCUM_PORT: 7777           # พอร์ตเริ่มต้น
      SCUM_MAX_PLAYERS: 128     # จำนวนผู้เล่นสูงสุด
      SCUM_NO_BATTLEYE: "false" # เปิด/ปิด BattlEye
      STEAM_APP_ID: "3792580"   # AppID ของ SCUM Dedicated Server
    restart: unless-stopped
