version: "3.8"

services:
  scum:
    build: .
    container_name: SCUM-SV1
    network_mode: host
    volumes:
      - /mnt/user/appdata/SCUM-SV1:/home/scum/SCUM
    environment:
      TZ: Asia/Bangkok
      STEAM_USER: 
      STEAM_PASS: 
      SCUM_PORT: 7777
      SCUM_MAX_PLAYERS: 128
      SCUM_NO_BATTLEYE: "false"
      STEAM_APP_ID: "3792580"
    restart: unless-stopped
